### ISSUE TITLE
error: Installation failed! / error: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by eugenpredescu** [vtex-apps/google-drive-import#51]
Hi,

I can't install this app, it says:

```
C:\Vtex\oigan (master)
λ vtex install vtex.google-drive-import
12:08:26.907 - error: Installation failed!
12:08:26.911 - error: Cannot read property 'forEach' of undefined
12:08:26.913 - warn: The following app was not installed: vtex.google-drive-import
```
Vtex account: fstudioqa

Thanks,

**Comment by btalma** [comment]
I could not reproduce the error.  It is installed.
09:16:44.676 - info: Starting to install app with accepted Terms
09:16:51.531 - info: Installed app vtex.google-drive-import successfully
